package DB;
// Generated Oct 14, 2016 12:43:12 AM by Hibernate Tools 3.6.0



/**
 * Address generated by hbm2java
 */
public class Address  implements java.io.Serializable {


     private Integer idaddress;
     private User user;
     private City city;
     private Province province;
     private District district;
     private String address1;
     private String address2;

    public Address() {
    }

	
    public Address(User user, City city, Province province, District district) {
        this.user = user;
        this.city = city;
        this.province = province;
        this.district = district;
    }
    public Address(User user, City city, Province province, District district, String address1, String address2) {
       this.user = user;
       this.city = city;
       this.province = province;
       this.district = district;
       this.address1 = address1;
       this.address2 = address2;
    }
   
    public Integer getIdaddress() {
        return this.idaddress;
    }
    
    public void setIdaddress(Integer idaddress) {
        this.idaddress = idaddress;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }
    public Province getProvince() {
        return this.province;
    }
    
    public void setProvince(Province province) {
        this.province = province;
    }
    public District getDistrict() {
        return this.district;
    }
    
    public void setDistrict(District district) {
        this.district = district;
    }
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }




}


