package DB;
// Generated Oct 5, 2016 1:19:24 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Address generated by hbm2java
 */
public class Address  implements java.io.Serializable {


     private Integer idaddress;
     private City city;
     private Province province;
     private District district;
     private String address1;
     private String address2;
     private Set users = new HashSet(0);

    public Address() {
    }

	
    public Address(City city, Province province, District district) {
        this.city = city;
        this.province = province;
        this.district = district;
    }
    public Address(City city, Province province, District district, String address1, String address2, Set users) {
       this.city = city;
       this.province = province;
       this.district = district;
       this.address1 = address1;
       this.address2 = address2;
       this.users = users;
    }
   
    public Integer getIdaddress() {
        return this.idaddress;
    }
    
    public void setIdaddress(Integer idaddress) {
        this.idaddress = idaddress;
    }
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }
    public Province getProvince() {
        return this.province;
    }
    
    public void setProvince(Province province) {
        this.province = province;
    }
    public District getDistrict() {
        return this.district;
    }
    
    public void setDistrict(District district) {
        this.district = district;
    }
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


