package DB;
// Generated Dec 21, 2016 2:58:47 AM by Hibernate Tools 3.6.0



/**
 * Adds generated by hbm2java
 */
public class Adds  implements java.io.Serializable {


     private Integer idadd;
     private String imgpath;

    public Adds() {
    }

    public Adds(String imgpath) {
       this.imgpath = imgpath;
    }
   
    public Integer getIdadd() {
        return this.idadd;
    }
    
    public void setIdadd(Integer idadd) {
        this.idadd = idadd;
    }
    public String getImgpath() {
        return this.imgpath;
    }
    
    public void setImgpath(String imgpath) {
        this.imgpath = imgpath;
    }




}


