package DB;
// Generated Dec 21, 2016 2:58:47 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Cart generated by hbm2java
 */
public class Cart  implements java.io.Serializable {


     private Integer idcart;
     private User user;
     private String date;
     private Set stockHasCarts = new HashSet(0);

    public Cart() {
    }

	
    public Cart(User user) {
        this.user = user;
    }
    public Cart(User user, String date, Set stockHasCarts) {
       this.user = user;
       this.date = date;
       this.stockHasCarts = stockHasCarts;
    }
   
    public Integer getIdcart() {
        return this.idcart;
    }
    
    public void setIdcart(Integer idcart) {
        this.idcart = idcart;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public Set getStockHasCarts() {
        return this.stockHasCarts;
    }
    
    public void setStockHasCarts(Set stockHasCarts) {
        this.stockHasCarts = stockHasCarts;
    }




}


