package DB;
// Generated Dec 13, 2016 4:10:11 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Catagory generated by hbm2java
 */
public class Catagory  implements java.io.Serializable {


     private Integer catagoryId;
     private String catagory;
     private Set stocks = new HashSet(0);

    public Catagory() {
    }

    public Catagory(String catagory, Set stocks) {
       this.catagory = catagory;
       this.stocks = stocks;
    }
   
    public Integer getCatagoryId() {
        return this.catagoryId;
    }
    
    public void setCatagoryId(Integer catagoryId) {
        this.catagoryId = catagoryId;
    }
    public String getCatagory() {
        return this.catagory;
    }
    
    public void setCatagory(String catagory) {
        this.catagory = catagory;
    }
    public Set getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set stocks) {
        this.stocks = stocks;
    }




}


