package DB;
// Generated Dec 21, 2016 2:58:47 AM by Hibernate Tools 3.6.0



/**
 * InvoiceItems generated by hbm2java
 */
public class InvoiceItems  implements java.io.Serializable {


     private Integer invItemsId;
     private Stock stock;
     private Invoice invoice;
     private Integer qty;
     private Double price;

    public InvoiceItems() {
    }

	
    public InvoiceItems(Stock stock, Invoice invoice) {
        this.stock = stock;
        this.invoice = invoice;
    }
    public InvoiceItems(Stock stock, Invoice invoice, Integer qty, Double price) {
       this.stock = stock;
       this.invoice = invoice;
       this.qty = qty;
       this.price = price;
    }
   
    public Integer getInvItemsId() {
        return this.invItemsId;
    }
    
    public void setInvItemsId(Integer invItemsId) {
        this.invItemsId = invItemsId;
    }
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }




}


