package DB;
// Generated Dec 21, 2016 2:58:47 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private Integer invoiceId;
     private User user;
     private Integer totalPrice;
     private Date date;
     private Set invoiceItemses = new HashSet(0);

    public Invoice() {
    }

	
    public Invoice(User user) {
        this.user = user;
    }
    public Invoice(User user, Integer totalPrice, Date date, Set invoiceItemses) {
       this.user = user;
       this.totalPrice = totalPrice;
       this.date = date;
       this.invoiceItemses = invoiceItemses;
    }
   
    public Integer getInvoiceId() {
        return this.invoiceId;
    }
    
    public void setInvoiceId(Integer invoiceId) {
        this.invoiceId = invoiceId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Integer getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(Integer totalPrice) {
        this.totalPrice = totalPrice;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Set getInvoiceItemses() {
        return this.invoiceItemses;
    }
    
    public void setInvoiceItemses(Set invoiceItemses) {
        this.invoiceItemses = invoiceItemses;
    }




}


