package DB;
// Generated Dec 21, 2016 2:58:47 AM by Hibernate Tools 3.6.0



/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private Integer orderid;
     private User user;
     private Stock stock;
     private String date;
     private Integer size;
     private int qty;
     private Integer status;

    public Orders() {
    }

	
    public Orders(User user, Stock stock, int qty) {
        this.user = user;
        this.stock = stock;
        this.qty = qty;
    }
    public Orders(User user, Stock stock, String date, Integer size, int qty, Integer status) {
       this.user = user;
       this.stock = stock;
       this.date = date;
       this.size = size;
       this.qty = qty;
       this.status = status;
    }
   
    public Integer getOrderid() {
        return this.orderid;
    }
    
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public Integer getSize() {
        return this.size;
    }
    
    public void setSize(Integer size) {
        this.size = size;
    }
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


