package DB;
// Generated Dec 21, 2016 2:58:47 AM by Hibernate Tools 3.6.0



/**
 * Pages generated by hbm2java
 */
public class Pages  implements java.io.Serializable {


     private Integer pageid;
     private String pagename;
     private Integer status;

    public Pages() {
    }

    public Pages(String pagename, Integer status) {
       this.pagename = pagename;
       this.status = status;
    }
   
    public Integer getPageid() {
        return this.pageid;
    }
    
    public void setPageid(Integer pageid) {
        this.pageid = pageid;
    }
    public String getPagename() {
        return this.pagename;
    }
    
    public void setPagename(String pagename) {
        this.pagename = pagename;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }




}


