package DB;
// Generated Oct 29, 2016 2:03:51 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Province generated by hbm2java
 */
public class Province  implements java.io.Serializable {


     private Integer proid;
     private String province;
     private Set addresses = new HashSet(0);
     private Set districts = new HashSet(0);

    public Province() {
    }

    public Province(String province, Set addresses, Set districts) {
       this.province = province;
       this.addresses = addresses;
       this.districts = districts;
    }
   
    public Integer getProid() {
        return this.proid;
    }
    
    public void setProid(Integer proid) {
        this.proid = proid;
    }
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }
    public Set getAddresses() {
        return this.addresses;
    }
    
    public void setAddresses(Set addresses) {
        this.addresses = addresses;
    }
    public Set getDistricts() {
        return this.districts;
    }
    
    public void setDistricts(Set districts) {
        this.districts = districts;
    }




}


