package DB;
// Generated Dec 13, 2016 4:10:11 AM by Hibernate Tools 3.6.0



/**
 * Size generated by hbm2java
 */
public class Size  implements java.io.Serializable {


     private Integer sizeid;
     private Stock stock;
     private Integer size;
     private Integer qty;

    public Size() {
    }

	
    public Size(Stock stock) {
        this.stock = stock;
    }
    public Size(Stock stock, Integer size, Integer qty) {
       this.stock = stock;
       this.size = size;
       this.qty = qty;
    }
   
    public Integer getSizeid() {
        return this.sizeid;
    }
    
    public void setSizeid(Integer sizeid) {
        this.sizeid = sizeid;
    }
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }
    public Integer getSize() {
        return this.size;
    }
    
    public void setSize(Integer size) {
        this.size = size;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }




}


