package DB;
// Generated Oct 14, 2016 12:43:12 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer uid;
     private UserType userType;
     private String fname;
     private String lname;
     private Integer tpnumber;
     private Integer status;
     private String email;
     private String password;
     private Set carts = new HashSet(0);
     private Set loginDetails = new HashSet(0);
     private Set addresses = new HashSet(0);
     private Set stocks = new HashSet(0);

    public User() {
    }

	
    public User(UserType userType) {
        this.userType = userType;
    }
    public User(UserType userType, String fname, String lname, Integer tpnumber, Integer status, String email, String password, Set carts, Set loginDetails, Set addresses, Set stocks) {
       this.userType = userType;
       this.fname = fname;
       this.lname = lname;
       this.tpnumber = tpnumber;
       this.status = status;
       this.email = email;
       this.password = password;
       this.carts = carts;
       this.loginDetails = loginDetails;
       this.addresses = addresses;
       this.stocks = stocks;
    }
   
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public Integer getTpnumber() {
        return this.tpnumber;
    }
    
    public void setTpnumber(Integer tpnumber) {
        this.tpnumber = tpnumber;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set carts) {
        this.carts = carts;
    }
    public Set getLoginDetails() {
        return this.loginDetails;
    }
    
    public void setLoginDetails(Set loginDetails) {
        this.loginDetails = loginDetails;
    }
    public Set getAddresses() {
        return this.addresses;
    }
    
    public void setAddresses(Set addresses) {
        this.addresses = addresses;
    }
    public Set getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set stocks) {
        this.stocks = stocks;
    }




}


