package DB;
// Generated Oct 5, 2016 1:19:24 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer uid;
     private Address address;
     private UserType userType;
     private String fname;
     private String lname;
     private Integer tpnumber;
     private Integer status;
     private Set carts = new HashSet(0);
     private Set logins = new HashSet(0);
     private Set stocks = new HashSet(0);

    public User() {
    }

	
    public User(Address address, UserType userType) {
        this.address = address;
        this.userType = userType;
    }
    public User(Address address, UserType userType, String fname, String lname, Integer tpnumber, Integer status, Set carts, Set logins, Set stocks) {
       this.address = address;
       this.userType = userType;
       this.fname = fname;
       this.lname = lname;
       this.tpnumber = tpnumber;
       this.status = status;
       this.carts = carts;
       this.logins = logins;
       this.stocks = stocks;
    }
   
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public Integer getTpnumber() {
        return this.tpnumber;
    }
    
    public void setTpnumber(Integer tpnumber) {
        this.tpnumber = tpnumber;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set carts) {
        this.carts = carts;
    }
    public Set getLogins() {
        return this.logins;
    }
    
    public void setLogins(Set logins) {
        this.logins = logins;
    }
    public Set getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set stocks) {
        this.stocks = stocks;
    }




}


