package DB;
// Generated Oct 5, 2016 3:08:36 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * UserType generated by hbm2java
 */
public class UserType  implements java.io.Serializable {


     private Integer usid;
     private String userType;
     private Set users = new HashSet(0);

    public UserType() {
    }

    public UserType(String userType, Set users) {
       this.userType = userType;
       this.users = users;
    }
   
    public Integer getUsid() {
        return this.usid;
    }
    
    public void setUsid(Integer usid) {
        this.usid = usid;
    }
    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


