package DB;
// Generated Dec 21, 2016 2:58:47 AM by Hibernate Tools 3.6.0



/**
 * Wishlist generated by hbm2java
 */
public class Wishlist  implements java.io.Serializable {


     private Integer idwishlist;
     private User user;
     private Stock stock;
     private String date;

    public Wishlist() {
    }

	
    public Wishlist(User user, Stock stock) {
        this.user = user;
        this.stock = stock;
    }
    public Wishlist(User user, Stock stock, String date) {
       this.user = user;
       this.stock = stock;
       this.date = date;
    }
   
    public Integer getIdwishlist() {
        return this.idwishlist;
    }
    
    public void setIdwishlist(Integer idwishlist) {
        this.idwishlist = idwishlist;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Stock getStock() {
        return this.stock;
    }
    
    public void setStock(Stock stock) {
        this.stock = stock;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }




}


